#!/usr/bin/ksh
#set -x
. ./ideploy.inc

ETH_CARD_SIZE_KEY="eth_card.size"
ETH_CARD_KEY="eth_card"
ETH_ALIAS_KEY="alias"
ETH_NEWIP_KEY="new_ip"
ETH_NETMASK_KEY="subnet_mask"
CARD_BOND_SIZE_KEY="card_bond.size"
CARD_BOND_KEY="card_bond"
CARD_BOND_IP_KEY="bond_ip"
CARD_BOND_NAME_KEY="bond_name"
CARD_BOND_ALIAS1_KEY="alias1"
CARD_BOND_ALIAS2_KEY="alias2"
CARD_BOND_NETMASK_KEY="bond_subnet_mask"
BUILD_TRUST_RELATION_HOSTIP_KEY="_hostip.1"
BUILD_TRUST_RELATION_USERNAME_KEY="_username.1"
HOST_TYPE_KEY="_hostType"
HOST_IP_KEY="_hostip"
OBTAIN_IP_POLICY="static"
IDEPLOY_DEFAULT_ETH_CARD_ALIAS="iDeployDefaultEthCardAlias"
IDEPLOY_DEFAULT_BOND_NAME="iDeployDefaultBondName"






